//! ONNX Parser for Mars Compiler
//!
//! Loads ONNX models via a JSON+binary format generated by onnx2mars.py.
//! This avoids protobuf parsing issues by using Python's reference onnx library.

use anyhow::{Context, Result, bail};
use serde::Deserialize;
use std::collections::HashMap;
use std::fs;
use std::path::Path;

// ============================================================================
// High-level types for Mars conversion
// ============================================================================

/// ONNX data types (simplified enum for our use)
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(i32)]
pub enum TensorDataType {
    Undefined = 0,
    Float = 1,
    Uint8 = 2,
    Int8 = 3,
    Uint16 = 4,
    Int16 = 5,
    Int32 = 6,
    Int64 = 7,
    String = 8,
    Bool = 9,
    Float16 = 10,
    Double = 11,
    Uint32 = 12,
    Uint64 = 13,
}

impl TensorDataType {
    pub fn from_i32(v: i32) -> Self {
        match v {
            1 => Self::Float,
            2 => Self::Uint8,
            3 => Self::Int8,
            6 => Self::Int32,
            7 => Self::Int64,
            10 => Self::Float16,
            11 => Self::Double,
            _ => Self::Undefined,
        }
    }

    pub fn element_size(&self) -> usize {
        match self {
            Self::Float | Self::Int32 | Self::Uint32 => 4,
            Self::Int64 | Self::Uint64 | Self::Double => 8,
            Self::Int16 | Self::Uint16 | Self::Float16 => 2,
            Self::Int8 | Self::Uint8 | Self::Bool => 1,
            _ => 4,
        }
    }
}

// ============================================================================
// High-level parsed structures for Mars conversion
// ============================================================================

/// Parsed ONNX tensor info
#[derive(Debug, Clone)]
pub struct OnnxTensor {
    pub name: String,
    pub dims: Vec<i64>,
    pub data_type: TensorDataType,
    pub data: Vec<u8>,
    pub float_data: Vec<f32>,  // For scalars stored in float_data field
}

impl OnnxTensor {
    pub fn num_elements(&self) -> usize {
        self.dims.iter().map(|&d| d as usize).product()
    }
}

/// Parsed ONNX node/operation
#[derive(Debug, Clone)]
pub struct OnnxNode {
    pub name: String,
    pub op_type: String,
    pub inputs: Vec<String>,
    pub outputs: Vec<String>,
    pub attributes: HashMap<String, OnnxAttribute>,
}

/// ONNX attribute value
#[derive(Debug, Clone)]
pub enum OnnxAttribute {
    Int(i64),
    Float(f32),
    String(String),
    Ints(Vec<i64>),
    Floats(Vec<f32>),
    Tensor(OnnxTensor),
}

impl OnnxNode {
    pub fn get_int(&self, name: &str) -> Option<i64> {
        match self.attributes.get(name) {
            Some(OnnxAttribute::Int(v)) => Some(*v),
            _ => None,
        }
    }

    pub fn get_ints(&self, name: &str) -> Option<&Vec<i64>> {
        match self.attributes.get(name) {
            Some(OnnxAttribute::Ints(v)) => Some(v),
            _ => None,
        }
    }

    pub fn get_float(&self, name: &str) -> Option<f32> {
        match self.attributes.get(name) {
            Some(OnnxAttribute::Float(v)) => Some(*v),
            _ => None,
        }
    }

    pub fn get_string(&self, name: &str) -> Option<&str> {
        match self.attributes.get(name) {
            Some(OnnxAttribute::String(v)) => Some(v),
            _ => None,
        }
    }
}

/// Input/output shape info
#[derive(Debug, Clone)]
pub struct TensorShape {
    pub name: String,
    pub dims: Vec<i64>,
    pub data_type: TensorDataType,
}

// TensorShape is now populated from JSON, no from_value_info needed

/// Complete parsed ONNX model
#[derive(Debug)]
pub struct OnnxModel {
    pub name: String,
    pub producer: String,
    pub opset_version: i64,
    pub inputs: Vec<TensorShape>,
    pub outputs: Vec<TensorShape>,
    pub nodes: Vec<OnnxNode>,
    pub initializers: HashMap<String, OnnxTensor>,
    pub shape_info: HashMap<String, Vec<i64>>,  // name -> shape for all tensors
}

// JSON structures from onnx2mars.py
#[derive(Debug, Deserialize)]
struct JsonValueInfo {
    name: String,
    dtype: i32,
    shape: Vec<i64>,
}

#[derive(Debug, Deserialize)]
struct JsonNode {
    op_type: String,
    name: String,
    inputs: Vec<String>,
    outputs: Vec<String>,
    attributes: HashMap<String, serde_json::Value>,
}

#[derive(Debug, Deserialize)]
struct JsonInitializer {
    name: String,
    dims: Vec<i64>,
    dtype: i32,
    data_offset: usize,
    data_len: usize,
}

#[derive(Debug, Deserialize)]
struct JsonManifest {
    opset: i64,
    inputs: Vec<JsonValueInfo>,
    outputs: Vec<JsonValueInfo>,
    nodes: Vec<JsonNode>,
    initializers: Vec<JsonInitializer>,
    weight_bytes: usize,
}

impl OnnxModel {
    /// Load model from JSON+binary format (generated by onnx2mars.py)
    pub fn load<P: AsRef<Path>>(path: P) -> Result<Self> {
        let path = path.as_ref();

        // Check if it's .onnx or .json
        let (json_path, bin_path) = if path.extension().map_or(false, |e| e == "onnx") {
            // Need to run onnx2mars.py first
            bail!("Direct ONNX loading not supported. Run onnx2mars.py first:\n  \
                   python3 onnx2mars.py {} -o {}",
                   path.display(),
                   path.with_extension("mars").display());
        } else if path.extension().map_or(false, |e| e == "json") {
            (path.to_path_buf(), path.with_extension("bin"))
        } else {
            // Assume .mars base name
            (path.with_extension("json"), path.with_extension("bin"))
        };

        // Load JSON manifest
        let json_data = fs::read_to_string(&json_path)
            .with_context(|| format!("Failed to read {}", json_path.display()))?;
        let manifest: JsonManifest = serde_json::from_str(&json_data)
            .with_context(|| format!("Failed to parse {}", json_path.display()))?;

        // Load binary weights
        let bin_data = fs::read(&bin_path)
            .with_context(|| format!("Failed to read {}", bin_path.display()))?;

        if bin_data.len() != manifest.weight_bytes {
            bail!("Weight file size mismatch: expected {} bytes, got {}",
                  manifest.weight_bytes, bin_data.len());
        }

        // Convert inputs
        let inputs: Vec<TensorShape> = manifest.inputs.iter()
            .map(|vi| TensorShape {
                name: vi.name.clone(),
                dims: vi.shape.clone(),
                data_type: TensorDataType::from_i32(vi.dtype),
            })
            .collect();

        // Convert outputs
        let outputs: Vec<TensorShape> = manifest.outputs.iter()
            .map(|vi| TensorShape {
                name: vi.name.clone(),
                dims: vi.shape.clone(),
                data_type: TensorDataType::from_i32(vi.dtype),
            })
            .collect();

        // Convert nodes
        let nodes: Vec<OnnxNode> = manifest.nodes.iter()
            .map(|n| {
                let mut attributes = HashMap::new();
                for (k, v) in &n.attributes {
                    let attr = match v {
                        serde_json::Value::Number(n) => {
                            if let Some(i) = n.as_i64() {
                                Some(OnnxAttribute::Int(i))
                            } else if let Some(f) = n.as_f64() {
                                Some(OnnxAttribute::Float(f as f32))
                            } else {
                                None
                            }
                        }
                        serde_json::Value::String(s) => Some(OnnxAttribute::String(s.clone())),
                        serde_json::Value::Array(arr) => {
                            if arr.first().map_or(false, |v| v.is_i64()) {
                                Some(OnnxAttribute::Ints(
                                    arr.iter().filter_map(|v| v.as_i64()).collect()
                                ))
                            } else if arr.first().map_or(false, |v| v.is_f64()) {
                                Some(OnnxAttribute::Floats(
                                    arr.iter().filter_map(|v| v.as_f64()).map(|f| f as f32).collect()
                                ))
                            } else {
                                None
                            }
                        }
                        _ => None,
                    };
                    if let Some(a) = attr {
                        attributes.insert(k.clone(), a);
                    }
                }
                OnnxNode {
                    name: n.name.clone(),
                    op_type: n.op_type.clone(),
                    inputs: n.inputs.clone(),
                    outputs: n.outputs.clone(),
                    attributes,
                }
            })
            .collect();

        // Convert initializers with actual weight data
        let mut initializers = HashMap::new();
        let mut shape_info = HashMap::new();

        for init in &manifest.initializers {
            let data = bin_data[init.data_offset..init.data_offset + init.data_len].to_vec();

            initializers.insert(init.name.clone(), OnnxTensor {
                name: init.name.clone(),
                dims: init.dims.clone(),
                data_type: TensorDataType::from_i32(init.dtype),
                data,
                float_data: Vec::new(),
            });

            shape_info.insert(init.name.clone(), init.dims.clone());
        }

        // Add input/output shapes to shape_info
        for input in &inputs {
            shape_info.insert(input.name.clone(), input.dims.clone());
        }
        for output in &outputs {
            shape_info.insert(output.name.clone(), output.dims.clone());
        }

        Ok(Self {
            name: json_path.file_stem()
                .map(|s| s.to_string_lossy().to_string())
                .unwrap_or_default(),
            producer: "onnx2mars.py".to_string(),
            opset_version: manifest.opset,
            inputs,
            outputs,
            nodes,
            initializers,
            shape_info,
        })
    }

    /// Print a summary of the model
    pub fn print_summary(&self) {
        println!("ONNX Model: {}", self.name);
        println!("Producer: {}", self.producer);
        println!("Opset: {}", self.opset_version);
        println!("\nInputs:");
        for input in &self.inputs {
            println!("  {} {:?} ({:?})", input.name, input.dims, input.data_type);
        }
        println!("\nOutputs:");
        for output in &self.outputs {
            println!("  {} {:?} ({:?})", output.name, output.dims, output.data_type);
        }
        println!("\nNodes: {}", self.nodes.len());

        // Count op types
        let mut op_counts: HashMap<&str, usize> = HashMap::new();
        for node in &self.nodes {
            *op_counts.entry(&node.op_type).or_insert(0) += 1;
        }
        let mut ops: Vec<_> = op_counts.into_iter().collect();
        ops.sort_by(|a, b| b.1.cmp(&a.1));
        for (op, count) in ops {
            println!("  {}: {}", op, count);
        }

        println!("\nInitializers: {}", self.initializers.len());
        let total_bytes: usize = self.initializers.values()
            .map(|t| t.data.len())
            .sum();
        println!("  Total weight bytes: {} ({:.2} MB)",
            total_bytes, total_bytes as f64 / 1024.0 / 1024.0);

        // Debug: print first few initializers
        for (name, tensor) in self.initializers.iter().take(3) {
            println!("  {} dims={:?} dtype={:?} data_len={}",
                     name, tensor.dims, tensor.data_type, tensor.data.len());
        }
    }
}

