obj-m += nna-aip-trace.o

# This Makefile is only for out-of-tree kernel module builds, e.g.:
#   make -C /path/to/linux-037afdf52721ff31f556a2d892efdcc05e355c82 \
#        M=$(PWD)/nna-aip-trace ARCH=mips CROSS_COMPILE=mipsel-linux- modules

